import { createElement } from 'lwc';
import Testingcmp from 'c/testingcmp';

describe('c-testingcmp test suite', () => {
    afterEach(() => {
        // The jsdom instance is shared across test cases in a single file so reset the DOM
        while (document.body.firstChild) {
            document.body.removeChild(document.body.firstChild);
        }
    });

    // it('TODO: test case generated by CLI command, please fill in test logic', () => {
    //     const element = createElement('c-testingcmp', {
    //         is: Testingcmp
    //     });
    //     document.body.appendChild(element);
    //     expect(1).toBe(2);
    // });

    test('Display first greeting', () => {
        const element = createElement('c-testingcmp', {
            is: Testingcmp
        });
        document.body.appendChild(element);
        console.log(document.body.innerHTML);
        const firstDiv = element.shadowRoot.querySelector('div.first');
        expect(firstDiv.textContent).toBe('Hello, World!');
    })
});